@startuml
!define GCPPUML https://raw.githubusercontent.com/aharper343/GCP-PlantUML/master/dist
!includeurl GCPPUML/common.puml
!includeurl GCPPUML/all.puml

GCP_TENSORFLOW(GCP_TensorFlow,GCP_TensorFlow)

GCP_PLATFORM(GCP_Platform,GCP_Platform)

GCP_ISTIO(GCP_Istio,GCP_Istio)

GCP_KUBERNETES(GCP_Kubernetes,GCP_Kubernetes)

GCP_PARTNER_INTERCONNECT(GCP_Partner_Interconnect,GCP_Partner_Interconnect)

GCP_VIRTUAL_PRIVATE_CLOUD(GCP_Virtual_Private_Cloud,GCP_Virtual_Private_Cloud)

GCP_CLOUD_FIREWALL_RULES(GCP_Cloud_Firewall_Rules,GCP_Cloud_Firewall_Rules)

GCP_CLOUD_CDN(GCP_Cloud_CDN,GCP_Cloud_CDN)

GCP_CLOUD_LOAD_BALANCING(GCP_Cloud_Load_Balancing,GCP_Cloud_Load_Balancing)

GCP_DEDICATED_INTERCONNECT(GCP_Dedicated_Interconnect,GCP_Dedicated_Interconnect)

GCP_CLOUD_DNS(GCP_Cloud_DNS,GCP_Cloud_DNS)

GCP_CLOUD_VPN(GCP_Cloud_VPN,GCP_Cloud_VPN)

GCP_CLOUD_ROUTER(GCP_Cloud_Router,GCP_Cloud_Router)

GCP_CLOUD_EXTERNAL_IP_ADDRESSES(GCP_Cloud_External_IP_Addresses,GCP_Cloud_External_IP_Addresses)

GCP_STANDARD_NETWORK_TIER(GCP_Standard_Network_Tier,GCP_Standard_Network_Tier)

GCP_CLOUD_NETWORK(GCP_Cloud_Network,GCP_Cloud_Network)

GCP_CLOUD_ROUTES(GCP_Cloud_Routes,GCP_Cloud_Routes)

GCP_PREMIUM_NETWORK_TIER(GCP_Premium_Network_Tier,GCP_Premium_Network_Tier)

GCP_CLOUD_ARMOR(GCP_Cloud_Armor,GCP_Cloud_Armor)

GCP_CLOUD_FILESTORE(GCP_Cloud_Filestore,GCP_Cloud_Filestore)

GCP_CLOUD_DATASTORE(GCP_Cloud_Datastore,GCP_Cloud_Datastore)

GCP_CLOUD_SQL(GCP_Cloud_SQL,GCP_Cloud_SQL)

GCP_CLOUD_STORAGE(GCP_Cloud_Storage,GCP_Cloud_Storage)

GCP_CLOUD_MEMORYSTORE(GCP_Cloud_Memorystore,GCP_Cloud_Memorystore)

GCP_CLOUD_BIGTABLE(GCP_Cloud_Bigtable,GCP_Cloud_Bigtable)

GCP_PERSISTENT_DISK(GCP_Persistent_Disk,GCP_Persistent_Disk)

GCP_CLOUD_SPANNER(GCP_Cloud_Spanner,GCP_Cloud_Spanner)

GCP_TRANSFER_APPLIANCE(GCP_Transfer_Appliance,GCP_Transfer_Appliance)

GCP_DEVELOPER_PORTAL(GCP_Developer_Portal,GCP_Developer_Portal)

GCP_API_MONETIZATION(GCP_API_Monetization,GCP_API_Monetization)

GCP_API_ANALYTICS(GCP_API_Analytics,GCP_API_Analytics)

GCP_CLOUD_ENDPOINTS(GCP_Cloud_Endpoints,GCP_Cloud_Endpoints)

GCP_APIGEE_SENSE(GCP_Apigee_Sense,GCP_Apigee_Sense)

GCP_APIGEE_API_PLATFORM(GCP_Apigee_API_Platform,GCP_Apigee_API_Platform)

GCP_CLOUD_IOT_CORE(GCP_Cloud_IoT_Core,GCP_Cloud_IoT_Core)

GCP_ADVANCED_SOLUTIONS_LAB(GCP_Advanced_Solutions_Lab,GCP_Advanced_Solutions_Lab)

GCP_CLOUD_SPEECH_API(GCP_Cloud_Speech_API,GCP_Cloud_Speech_API)

GCP_CLOUD_TRANSLATION_API(GCP_Cloud_Translation_API,GCP_Cloud_Translation_API)

GCP_CLOUD_VIDEO_INTELLIGENCE_API(GCP_Cloud_Video_Intelligence_API,GCP_Cloud_Video_Intelligence_API)

GCP_CLOUD_AUTOML(GCP_Cloud_AutoML,GCP_Cloud_AutoML)

GCP_CLOUD_VISION_API(GCP_Cloud_Vision_API,GCP_Cloud_Vision_API)

GCP_CLOUD_NATURAL_LANGUAGE_API(GCP_Cloud_Natural_Language_API,GCP_Cloud_Natural_Language_API)

GCP_DIALOGFLOW_ENTERPRISE_EDITION(GCP_Dialogflow_Enterprise_Edition,GCP_Dialogflow_Enterprise_Edition)

GCP_CLOUD_MACHINE_LEARNING(GCP_Cloud_Machine_Learning,GCP_Cloud_Machine_Learning)

GCP_CLOUD_TPU(GCP_Cloud_TPU,GCP_Cloud_TPU)

GCP_CLOUD_TEXT_TO_SPEECH(GCP_Cloud_Text_to_Speech,GCP_Cloud_Text_to_Speech)

GCP_CLOUD_JOBS_API(GCP_Cloud_Jobs_API,GCP_Cloud_Jobs_API)

GCP_STACKDRIVER(GCP_Stackdriver,GCP_Stackdriver)

GCP_LOGGING(GCP_Logging,GCP_Logging)

GCP_CLOUD_DEPLOYMENT_MANAGER(GCP_Cloud_Deployment_Manager,GCP_Cloud_Deployment_Manager)

GCP_CLOUD_MOBILE_APP(GCP_Cloud_Mobile_App,GCP_Cloud_Mobile_App)

GCP_ERROR_REPORTING(GCP_Error_Reporting,GCP_Error_Reporting)

GCP_MONITORING(GCP_Monitoring,GCP_Monitoring)

GCP_CLOUD_SHELL(GCP_Cloud_Shell,GCP_Cloud_Shell)

GCP_TRACE(GCP_Trace,GCP_Trace)

GCP_CLOUD_CONSOLE(GCP_Cloud_Console,GCP_Cloud_Console)

GCP_CLOUD_APIS(GCP_Cloud_APIs,GCP_Cloud_APIs)

GCP_DEBUGGER(GCP_Debugger,GCP_Debugger)

GCP_CLOUD_BILLING_API(GCP_Cloud_Billing_API,GCP_Cloud_Billing_API)

GCP_CLOUD_SDK(GCP_Cloud_SDK,GCP_Cloud_SDK)

GCP_CLOUD_DEPLOYMENT_MANAGER(GCP_Cloud_Deployment_Manager,GCP_Cloud_Deployment_Manager)

GCP_CONTAINER_BUILDER(GCP_Container_Builder,GCP_Container_Builder)

GCP_CLOUD_SOURCE_REPOSITORIES(GCP_Cloud_Source_Repositories,GCP_Cloud_Source_Repositories)

GCP_CONTAINER_REGISTRY(GCP_Container_Registry,GCP_Container_Registry)

GCP_CLOUD_TEST_LAB(GCP_Cloud_Test_Lab,GCP_Cloud_Test_Lab)

GCP_CLOUD_SECURITY_SCANNER(GCP_Cloud_Security_Scanner,GCP_Cloud_Security_Scanner)

GCP_CLOUD_IAM(GCP_Cloud_IAM,GCP_Cloud_IAM)

GCP_SECURITY_KEY_ENFORCEMENT(GCP_Security_Key_Enforcement,GCP_Security_Key_Enforcement)

GCP_KEY_MANAGEMENT_SERVICE(GCP_Key_Management_Service,GCP_Key_Management_Service)

GCP_IDENTITY_AWARE_PROXY(GCP_Identity_Aware_Proxy,GCP_Identity_Aware_Proxy)

GCP_DATA_LOSS_PREVENTION_API(GCP_Data_Loss_Prevention_API,GCP_Data_Loss_Prevention_API)

GCP_CLOUD_SECURITY_COMMAND_CENTER(GCP_Cloud_Security_Command_Center,GCP_Cloud_Security_Command_Center)

GCP_BEYONDCORP(GCP_BeyondCorp,GCP_BeyondCorp)

GCP_CLOUD_RESOURCE_MANAGER(GCP_Cloud_Resource_Manager,GCP_Cloud_Resource_Manager)

GCP_CLOUD_FUNCTIONS(GCP_Cloud_Functions,GCP_Cloud_Functions)

GCP_CONTAINER_ENGINE(GCP_Container_Engine,GCP_Container_Engine)

GCP_APP_ENGINE(GCP_App_Engine,GCP_App_Engine)

GCP_COMPUTE_ENGINE(GCP_Compute_Engine,GCP_Compute_Engine)

GCP_GPU(GCP_GPU,GCP_GPU)

GCP_CONTAINER_OPTIMIZED_OS(GCP_Container_Optimized_OS,GCP_Container_Optimized_OS)

GCP_DATA_STUDIO(GCP_Data_Studio,GCP_Data_Studio)

GCP_CLOUD_PUBSUB(GCP_Cloud_PubSub,GCP_Cloud_PubSub)

GCP_CLOUD_DATAPREP(GCP_Cloud_Dataprep,GCP_Cloud_Dataprep)

GCP_BIGQUERY(GCP_BigQuery,GCP_BigQuery)

GCP_GENOMICS(GCP_Genomics,GCP_Genomics)

GCP_CLOUD_COMPOSER(GCP_Cloud_Composer,GCP_Cloud_Composer)

GCP_CLOUD_DATALAB(GCP_Cloud_Datalab,GCP_Cloud_Datalab)

GCP_CLOUD_DATAPROC(GCP_Cloud_Dataproc,GCP_Cloud_Dataproc)

GCP_CLOUD_DATAFLOW(GCP_Cloud_Dataflow,GCP_Cloud_Dataflow)

@enduml
