@startuml
!define PUML https://raw.githubusercontent.com/aharper343/GCP-PlantUML/master/dist
!includeurl PUML/common.puml


!includeurl PUML/GCP_Istio/GCP_Istio_LARGE.puml
GCP_ISTIO_LARGE(GCP_Istio_LARGE,GCP_Istio_LARGE)
!includeurl PUML/GCP_TensorFlow/GCP_TensorFlow_LARGE.puml
GCP_TENSORFLOW_LARGE(GCP_TensorFlow_LARGE,GCP_TensorFlow_LARGE)
!includeurl PUML/GCP_Kubernetes/GCP_Kubernetes_LARGE.puml
GCP_KUBERNETES_LARGE(GCP_Kubernetes_LARGE,GCP_Kubernetes_LARGE)
!includeurl PUML/GCP_Platform/GCP_Platform_LARGE.puml
GCP_PLATFORM_LARGE(GCP_Platform_LARGE,GCP_Platform_LARGE)
!includeurl PUML/Networking/GCP_Standard_Network_Tier/GCP_Standard_Network_Tier_LARGE.puml
GCP_STANDARD_NETWORK_TIER_LARGE(GCP_Standard_Network_Tier_LARGE,GCP_Standard_Network_Tier_LARGE)
!includeurl PUML/Networking/GCP_Cloud_Load_Balancing/GCP_Cloud_Load_Balancing_LARGE.puml
GCP_CLOUD_LOAD_BALANCING_LARGE(GCP_Cloud_Load_Balancing_LARGE,GCP_Cloud_Load_Balancing_LARGE)
!includeurl PUML/Networking/GCP_Cloud_Network/GCP_Cloud_Network_LARGE.puml
GCP_CLOUD_NETWORK_LARGE(GCP_Cloud_Network_LARGE,GCP_Cloud_Network_LARGE)
!includeurl PUML/Networking/GCP_Cloud_Armor/GCP_Cloud_Armor_LARGE.puml
GCP_CLOUD_ARMOR_LARGE(GCP_Cloud_Armor_LARGE,GCP_Cloud_Armor_LARGE)
!includeurl PUML/Networking/GCP_Cloud_VPN/GCP_Cloud_VPN_LARGE.puml
GCP_CLOUD_VPN_LARGE(GCP_Cloud_VPN_LARGE,GCP_Cloud_VPN_LARGE)
!includeurl PUML/Networking/GCP_Cloud_External_IP_Addresses/GCP_Cloud_External_IP_Addresses_LARGE.puml
GCP_CLOUD_EXTERNAL_IP_ADDRESSES_LARGE(GCP_Cloud_External_IP_Addresses_LARGE,GCP_Cloud_External_IP_Addresses_LARGE)
!includeurl PUML/Networking/GCP_Partner_Interconnect/GCP_Partner_Interconnect_LARGE.puml
GCP_PARTNER_INTERCONNECT_LARGE(GCP_Partner_Interconnect_LARGE,GCP_Partner_Interconnect_LARGE)
!includeurl PUML/Networking/GCP_Virtual_Private_Cloud/GCP_Virtual_Private_Cloud_LARGE.puml
GCP_VIRTUAL_PRIVATE_CLOUD_LARGE(GCP_Virtual_Private_Cloud_LARGE,GCP_Virtual_Private_Cloud_LARGE)
!includeurl PUML/Networking/GCP_Cloud_DNS/GCP_Cloud_DNS_LARGE.puml
GCP_CLOUD_DNS_LARGE(GCP_Cloud_DNS_LARGE,GCP_Cloud_DNS_LARGE)
!includeurl PUML/Networking/GCP_Premium_Network_Tier/GCP_Premium_Network_Tier_LARGE.puml
GCP_PREMIUM_NETWORK_TIER_LARGE(GCP_Premium_Network_Tier_LARGE,GCP_Premium_Network_Tier_LARGE)
!includeurl PUML/Networking/GCP_Cloud_Firewall_Rules/GCP_Cloud_Firewall_Rules_LARGE.puml
GCP_CLOUD_FIREWALL_RULES_LARGE(GCP_Cloud_Firewall_Rules_LARGE,GCP_Cloud_Firewall_Rules_LARGE)
!includeurl PUML/Networking/GCP_Cloud_CDN/GCP_Cloud_CDN_LARGE.puml
GCP_CLOUD_CDN_LARGE(GCP_Cloud_CDN_LARGE,GCP_Cloud_CDN_LARGE)
!includeurl PUML/Networking/GCP_Cloud_Routes/GCP_Cloud_Routes_LARGE.puml
GCP_CLOUD_ROUTES_LARGE(GCP_Cloud_Routes_LARGE,GCP_Cloud_Routes_LARGE)
!includeurl PUML/Networking/GCP_Dedicated_Interconnect/GCP_Dedicated_Interconnect_LARGE.puml
GCP_DEDICATED_INTERCONNECT_LARGE(GCP_Dedicated_Interconnect_LARGE,GCP_Dedicated_Interconnect_LARGE)
!includeurl PUML/Networking/GCP_Cloud_Router/GCP_Cloud_Router_LARGE.puml
GCP_CLOUD_ROUTER_LARGE(GCP_Cloud_Router_LARGE,GCP_Cloud_Router_LARGE)
!includeurl PUML/Storage_And_Databases/GCP_Cloud_Bigtable/GCP_Cloud_Bigtable_LARGE.puml
GCP_CLOUD_BIGTABLE_LARGE(GCP_Cloud_Bigtable_LARGE,GCP_Cloud_Bigtable_LARGE)
!includeurl PUML/Storage_And_Databases/GCP_Cloud_Spanner/GCP_Cloud_Spanner_LARGE.puml
GCP_CLOUD_SPANNER_LARGE(GCP_Cloud_Spanner_LARGE,GCP_Cloud_Spanner_LARGE)
!includeurl PUML/Storage_And_Databases/GCP_Cloud_SQL/GCP_Cloud_SQL_LARGE.puml
GCP_CLOUD_SQL_LARGE(GCP_Cloud_SQL_LARGE,GCP_Cloud_SQL_LARGE)
!includeurl PUML/Storage_And_Databases/GCP_Persistent_Disk/GCP_Persistent_Disk_LARGE.puml
GCP_PERSISTENT_DISK_LARGE(GCP_Persistent_Disk_LARGE,GCP_Persistent_Disk_LARGE)
!includeurl PUML/Storage_And_Databases/GCP_Cloud_Memorystore/GCP_Cloud_Memorystore_LARGE.puml
GCP_CLOUD_MEMORYSTORE_LARGE(GCP_Cloud_Memorystore_LARGE,GCP_Cloud_Memorystore_LARGE)
!includeurl PUML/Storage_And_Databases/GCP_Cloud_Filestore/GCP_Cloud_Filestore_LARGE.puml
GCP_CLOUD_FILESTORE_LARGE(GCP_Cloud_Filestore_LARGE,GCP_Cloud_Filestore_LARGE)
!includeurl PUML/Storage_And_Databases/GCP_Cloud_Storage/GCP_Cloud_Storage_LARGE.puml
GCP_CLOUD_STORAGE_LARGE(GCP_Cloud_Storage_LARGE,GCP_Cloud_Storage_LARGE)
!includeurl PUML/Storage_And_Databases/GCP_Cloud_Datastore/GCP_Cloud_Datastore_LARGE.puml
GCP_CLOUD_DATASTORE_LARGE(GCP_Cloud_Datastore_LARGE,GCP_Cloud_Datastore_LARGE)
!includeurl PUML/Data_Transfer/GCP_Transfer_Appliance/GCP_Transfer_Appliance_LARGE.puml
GCP_TRANSFER_APPLIANCE_LARGE(GCP_Transfer_Appliance_LARGE,GCP_Transfer_Appliance_LARGE)
!includeurl PUML/API_Platform_And_Ecosystems/GCP_Cloud_Endpoints/GCP_Cloud_Endpoints_LARGE.puml
GCP_CLOUD_ENDPOINTS_LARGE(GCP_Cloud_Endpoints_LARGE,GCP_Cloud_Endpoints_LARGE)
!includeurl PUML/API_Platform_And_Ecosystems/GCP_API_Monetization/GCP_API_Monetization_LARGE.puml
GCP_API_MONETIZATION_LARGE(GCP_API_Monetization_LARGE,GCP_API_Monetization_LARGE)
!includeurl PUML/API_Platform_And_Ecosystems/GCP_API_Analytics/GCP_API_Analytics_LARGE.puml
GCP_API_ANALYTICS_LARGE(GCP_API_Analytics_LARGE,GCP_API_Analytics_LARGE)
!includeurl PUML/API_Platform_And_Ecosystems/GCP_Apigee_Sense/GCP_Apigee_Sense_LARGE.puml
GCP_APIGEE_SENSE_LARGE(GCP_Apigee_Sense_LARGE,GCP_Apigee_Sense_LARGE)
!includeurl PUML/API_Platform_And_Ecosystems/GCP_Apigee_API_Platform/GCP_Apigee_API_Platform_LARGE.puml
GCP_APIGEE_API_PLATFORM_LARGE(GCP_Apigee_API_Platform_LARGE,GCP_Apigee_API_Platform_LARGE)
!includeurl PUML/API_Platform_And_Ecosystems/GCP_Developer_Portal/GCP_Developer_Portal_LARGE.puml
GCP_DEVELOPER_PORTAL_LARGE(GCP_Developer_Portal_LARGE,GCP_Developer_Portal_LARGE)
!includeurl PUML/Internet_of_Things/GCP_Cloud_IoT_Core/GCP_Cloud_IoT_Core_LARGE.puml
GCP_CLOUD_IOT_CORE_LARGE(GCP_Cloud_IoT_Core_LARGE,GCP_Cloud_IoT_Core_LARGE)
!includeurl PUML/Cloud_AI/GCP_Cloud_Machine_Learning/GCP_Cloud_Machine_Learning_LARGE.puml
GCP_CLOUD_MACHINE_LEARNING_LARGE(GCP_Cloud_Machine_Learning_LARGE,GCP_Cloud_Machine_Learning_LARGE)
!includeurl PUML/Cloud_AI/GCP_Cloud_Video_Intelligence_API/GCP_Cloud_Video_Intelligence_API_LARGE.puml
GCP_CLOUD_VIDEO_INTELLIGENCE_API_LARGE(GCP_Cloud_Video_Intelligence_API_LARGE,GCP_Cloud_Video_Intelligence_API_LARGE)
!includeurl PUML/Cloud_AI/GCP_Cloud_Translation_API/GCP_Cloud_Translation_API_LARGE.puml
GCP_CLOUD_TRANSLATION_API_LARGE(GCP_Cloud_Translation_API_LARGE,GCP_Cloud_Translation_API_LARGE)
!includeurl PUML/Cloud_AI/GCP_Dialogflow_Enterprise_Edition/GCP_Dialogflow_Enterprise_Edition_LARGE.puml
GCP_DIALOGFLOW_ENTERPRISE_EDITION_LARGE(GCP_Dialogflow_Enterprise_Edition_LARGE,GCP_Dialogflow_Enterprise_Edition_LARGE)
!includeurl PUML/Cloud_AI/GCP_Cloud_AutoML/GCP_Cloud_AutoML_LARGE.puml
GCP_CLOUD_AUTOML_LARGE(GCP_Cloud_AutoML_LARGE,GCP_Cloud_AutoML_LARGE)
!includeurl PUML/Cloud_AI/GCP_Cloud_Text_to_Speech/GCP_Cloud_Text_to_Speech_LARGE.puml
GCP_CLOUD_TEXT_TO_SPEECH_LARGE(GCP_Cloud_Text_to_Speech_LARGE,GCP_Cloud_Text_to_Speech_LARGE)
!includeurl PUML/Cloud_AI/GCP_Cloud_TPU/GCP_Cloud_TPU_LARGE.puml
GCP_CLOUD_TPU_LARGE(GCP_Cloud_TPU_LARGE,GCP_Cloud_TPU_LARGE)
!includeurl PUML/Cloud_AI/GCP_Cloud_Vision_API/GCP_Cloud_Vision_API_LARGE.puml
GCP_CLOUD_VISION_API_LARGE(GCP_Cloud_Vision_API_LARGE,GCP_Cloud_Vision_API_LARGE)
!includeurl PUML/Cloud_AI/GCP_Cloud_Jobs_API/GCP_Cloud_Jobs_API_LARGE.puml
GCP_CLOUD_JOBS_API_LARGE(GCP_Cloud_Jobs_API_LARGE,GCP_Cloud_Jobs_API_LARGE)
!includeurl PUML/Cloud_AI/GCP_Cloud_Speech_API/GCP_Cloud_Speech_API_LARGE.puml
GCP_CLOUD_SPEECH_API_LARGE(GCP_Cloud_Speech_API_LARGE,GCP_Cloud_Speech_API_LARGE)
!includeurl PUML/Cloud_AI/GCP_Cloud_Natural_Language_API/GCP_Cloud_Natural_Language_API_LARGE.puml
GCP_CLOUD_NATURAL_LANGUAGE_API_LARGE(GCP_Cloud_Natural_Language_API_LARGE,GCP_Cloud_Natural_Language_API_LARGE)
!includeurl PUML/Cloud_AI/GCP_Advanced_Solutions_Lab/GCP_Advanced_Solutions_Lab_LARGE.puml
GCP_ADVANCED_SOLUTIONS_LAB_LARGE(GCP_Advanced_Solutions_Lab_LARGE,GCP_Advanced_Solutions_Lab_LARGE)
!includeurl PUML/Management_Tools/GCP_Monitoring/GCP_Monitoring_LARGE.puml
GCP_MONITORING_LARGE(GCP_Monitoring_LARGE,GCP_Monitoring_LARGE)
!includeurl PUML/Management_Tools/GCP_Cloud_Mobile_App/GCP_Cloud_Mobile_App_LARGE.puml
GCP_CLOUD_MOBILE_APP_LARGE(GCP_Cloud_Mobile_App_LARGE,GCP_Cloud_Mobile_App_LARGE)
!includeurl PUML/Management_Tools/GCP_Cloud_Deployment_Manager/GCP_Cloud_Deployment_Manager_LARGE.puml
GCP_CLOUD_DEPLOYMENT_MANAGER_LARGE(GCP_Cloud_Deployment_Manager_LARGE,GCP_Cloud_Deployment_Manager_LARGE)
!includeurl PUML/Management_Tools/GCP_Trace/GCP_Trace_LARGE.puml
GCP_TRACE_LARGE(GCP_Trace_LARGE,GCP_Trace_LARGE)
!includeurl PUML/Management_Tools/GCP_Cloud_Console/GCP_Cloud_Console_LARGE.puml
GCP_CLOUD_CONSOLE_LARGE(GCP_Cloud_Console_LARGE,GCP_Cloud_Console_LARGE)
!includeurl PUML/Management_Tools/GCP_Cloud_Shell/GCP_Cloud_Shell_LARGE.puml
GCP_CLOUD_SHELL_LARGE(GCP_Cloud_Shell_LARGE,GCP_Cloud_Shell_LARGE)
!includeurl PUML/Management_Tools/GCP_Cloud_Billing_API/GCP_Cloud_Billing_API_LARGE.puml
GCP_CLOUD_BILLING_API_LARGE(GCP_Cloud_Billing_API_LARGE,GCP_Cloud_Billing_API_LARGE)
!includeurl PUML/Management_Tools/GCP_Stackdriver/GCP_Stackdriver_LARGE.puml
GCP_STACKDRIVER_LARGE(GCP_Stackdriver_LARGE,GCP_Stackdriver_LARGE)
!includeurl PUML/Management_Tools/GCP_Cloud_APIs/GCP_Cloud_APIs_LARGE.puml
GCP_CLOUD_APIS_LARGE(GCP_Cloud_APIs_LARGE,GCP_Cloud_APIs_LARGE)
!includeurl PUML/Management_Tools/GCP_Error_Reporting/GCP_Error_Reporting_LARGE.puml
GCP_ERROR_REPORTING_LARGE(GCP_Error_Reporting_LARGE,GCP_Error_Reporting_LARGE)
!includeurl PUML/Management_Tools/GCP_Debugger/GCP_Debugger_LARGE.puml
GCP_DEBUGGER_LARGE(GCP_Debugger_LARGE,GCP_Debugger_LARGE)
!includeurl PUML/Management_Tools/GCP_Logging/GCP_Logging_LARGE.puml
GCP_LOGGING_LARGE(GCP_Logging_LARGE,GCP_Logging_LARGE)
!includeurl PUML/Developer_Tools/GCP_Container_Builder/GCP_Container_Builder_LARGE.puml
GCP_CONTAINER_BUILDER_LARGE(GCP_Container_Builder_LARGE,GCP_Container_Builder_LARGE)
!includeurl PUML/Developer_Tools/GCP_Cloud_Source_Repositories/GCP_Cloud_Source_Repositories_LARGE.puml
GCP_CLOUD_SOURCE_REPOSITORIES_LARGE(GCP_Cloud_Source_Repositories_LARGE,GCP_Cloud_Source_Repositories_LARGE)
!includeurl PUML/Developer_Tools/GCP_Cloud_Test_Lab/GCP_Cloud_Test_Lab_LARGE.puml
GCP_CLOUD_TEST_LAB_LARGE(GCP_Cloud_Test_Lab_LARGE,GCP_Cloud_Test_Lab_LARGE)
!includeurl PUML/Developer_Tools/GCP_Cloud_SDK/GCP_Cloud_SDK_LARGE.puml
GCP_CLOUD_SDK_LARGE(GCP_Cloud_SDK_LARGE,GCP_Cloud_SDK_LARGE)
!includeurl PUML/Developer_Tools/GCP_Container_Registry/GCP_Container_Registry_LARGE.puml
GCP_CONTAINER_REGISTRY_LARGE(GCP_Container_Registry_LARGE,GCP_Container_Registry_LARGE)
!includeurl PUML/Developer_Tools/GCP_Cloud_Deployment_Manager/GCP_Cloud_Deployment_Manager_LARGE.puml
GCP_CLOUD_DEPLOYMENT_MANAGER_LARGE(GCP_Cloud_Deployment_Manager_LARGE,GCP_Cloud_Deployment_Manager_LARGE)
!includeurl PUML/Identity_And_Security/GCP_Cloud_Resource_Manager/GCP_Cloud_Resource_Manager_LARGE.puml
GCP_CLOUD_RESOURCE_MANAGER_LARGE(GCP_Cloud_Resource_Manager_LARGE,GCP_Cloud_Resource_Manager_LARGE)
!includeurl PUML/Identity_And_Security/GCP_BeyondCorp/GCP_BeyondCorp_LARGE.puml
GCP_BEYONDCORP_LARGE(GCP_BeyondCorp_LARGE,GCP_BeyondCorp_LARGE)
!includeurl PUML/Identity_And_Security/GCP_Key_Management_Service/GCP_Key_Management_Service_LARGE.puml
GCP_KEY_MANAGEMENT_SERVICE_LARGE(GCP_Key_Management_Service_LARGE,GCP_Key_Management_Service_LARGE)
!includeurl PUML/Identity_And_Security/GCP_Identity_Aware_Proxy/GCP_Identity_Aware_Proxy_LARGE.puml
GCP_IDENTITY_AWARE_PROXY_LARGE(GCP_Identity_Aware_Proxy_LARGE,GCP_Identity_Aware_Proxy_LARGE)
!includeurl PUML/Identity_And_Security/GCP_Cloud_Security_Command_Center/GCP_Cloud_Security_Command_Center_LARGE.puml
GCP_CLOUD_SECURITY_COMMAND_CENTER_LARGE(GCP_Cloud_Security_Command_Center_LARGE,GCP_Cloud_Security_Command_Center_LARGE)
!includeurl PUML/Identity_And_Security/GCP_Data_Loss_Prevention_API/GCP_Data_Loss_Prevention_API_LARGE.puml
GCP_DATA_LOSS_PREVENTION_API_LARGE(GCP_Data_Loss_Prevention_API_LARGE,GCP_Data_Loss_Prevention_API_LARGE)
!includeurl PUML/Identity_And_Security/GCP_Security_Key_Enforcement/GCP_Security_Key_Enforcement_LARGE.puml
GCP_SECURITY_KEY_ENFORCEMENT_LARGE(GCP_Security_Key_Enforcement_LARGE,GCP_Security_Key_Enforcement_LARGE)
!includeurl PUML/Identity_And_Security/GCP_Cloud_Security_Scanner/GCP_Cloud_Security_Scanner_LARGE.puml
GCP_CLOUD_SECURITY_SCANNER_LARGE(GCP_Cloud_Security_Scanner_LARGE,GCP_Cloud_Security_Scanner_LARGE)
!includeurl PUML/Identity_And_Security/GCP_Cloud_IAM/GCP_Cloud_IAM_LARGE.puml
GCP_CLOUD_IAM_LARGE(GCP_Cloud_IAM_LARGE,GCP_Cloud_IAM_LARGE)
!includeurl PUML/Compute/GCP_Compute_Engine/GCP_Compute_Engine_LARGE.puml
GCP_COMPUTE_ENGINE_LARGE(GCP_Compute_Engine_LARGE,GCP_Compute_Engine_LARGE)
!includeurl PUML/Compute/GCP_Container_Engine/GCP_Container_Engine_LARGE.puml
GCP_CONTAINER_ENGINE_LARGE(GCP_Container_Engine_LARGE,GCP_Container_Engine_LARGE)
!includeurl PUML/Compute/GCP_Cloud_Functions/GCP_Cloud_Functions_LARGE.puml
GCP_CLOUD_FUNCTIONS_LARGE(GCP_Cloud_Functions_LARGE,GCP_Cloud_Functions_LARGE)
!includeurl PUML/Compute/GCP_App_Engine/GCP_App_Engine_LARGE.puml
GCP_APP_ENGINE_LARGE(GCP_App_Engine_LARGE,GCP_App_Engine_LARGE)
!includeurl PUML/Compute/GCP_Container_Optimized_OS/GCP_Container_Optimized_OS_LARGE.puml
GCP_CONTAINER_OPTIMIZED_OS_LARGE(GCP_Container_Optimized_OS_LARGE,GCP_Container_Optimized_OS_LARGE)
!includeurl PUML/Compute/GCP_GPU/GCP_GPU_LARGE.puml
GCP_GPU_LARGE(GCP_GPU_LARGE,GCP_GPU_LARGE)
!includeurl PUML/Big_Data/GCP_Cloud_Composer/GCP_Cloud_Composer_LARGE.puml
GCP_CLOUD_COMPOSER_LARGE(GCP_Cloud_Composer_LARGE,GCP_Cloud_Composer_LARGE)
!includeurl PUML/Big_Data/GCP_BigQuery/GCP_BigQuery_LARGE.puml
GCP_BIGQUERY_LARGE(GCP_BigQuery_LARGE,GCP_BigQuery_LARGE)
!includeurl PUML/Big_Data/GCP_Data_Studio/GCP_Data_Studio_LARGE.puml
GCP_DATA_STUDIO_LARGE(GCP_Data_Studio_LARGE,GCP_Data_Studio_LARGE)
!includeurl PUML/Big_Data/GCP_Cloud_Datalab/GCP_Cloud_Datalab_LARGE.puml
GCP_CLOUD_DATALAB_LARGE(GCP_Cloud_Datalab_LARGE,GCP_Cloud_Datalab_LARGE)
!includeurl PUML/Big_Data/GCP_Cloud_Dataproc/GCP_Cloud_Dataproc_LARGE.puml
GCP_CLOUD_DATAPROC_LARGE(GCP_Cloud_Dataproc_LARGE,GCP_Cloud_Dataproc_LARGE)
!includeurl PUML/Big_Data/GCP_Cloud_Dataflow/GCP_Cloud_Dataflow_LARGE.puml
GCP_CLOUD_DATAFLOW_LARGE(GCP_Cloud_Dataflow_LARGE,GCP_Cloud_Dataflow_LARGE)
!includeurl PUML/Big_Data/GCP_Cloud_Dataprep/GCP_Cloud_Dataprep_LARGE.puml
GCP_CLOUD_DATAPREP_LARGE(GCP_Cloud_Dataprep_LARGE,GCP_Cloud_Dataprep_LARGE)
!includeurl PUML/Big_Data/GCP_Genomics/GCP_Genomics_LARGE.puml
GCP_GENOMICS_LARGE(GCP_Genomics_LARGE,GCP_Genomics_LARGE)
!includeurl PUML/Big_Data/GCP_Cloud_PubSub/GCP_Cloud_PubSub_LARGE.puml
GCP_CLOUD_PUBSUB_LARGE(GCP_Cloud_PubSub_LARGE,GCP_Cloud_PubSub_LARGE)

@enduml
