@startuml
!define GCPPUML https://raw.githubusercontent.com/aharper343/GCP-PlantUML/master/dist
!includeurl GCPPUML/common.puml
!includeurl GCPPUML/all_LARGE.puml


GCP_ISTIO_LARGE(GCP_Istio_LARGE,GCP_Istio_LARGE)
GCP_TENSORFLOW_LARGE(GCP_TensorFlow_LARGE,GCP_TensorFlow_LARGE)
GCP_KUBERNETES_LARGE(GCP_Kubernetes_LARGE,GCP_Kubernetes_LARGE)
GCP_PLATFORM_LARGE(GCP_Platform_LARGE,GCP_Platform_LARGE)
GCP_STANDARD_NETWORK_TIER_LARGE(GCP_Standard_Network_Tier_LARGE,GCP_Standard_Network_Tier_LARGE)
GCP_CLOUD_LOAD_BALANCING_LARGE(GCP_Cloud_Load_Balancing_LARGE,GCP_Cloud_Load_Balancing_LARGE)
GCP_CLOUD_NETWORK_LARGE(GCP_Cloud_Network_LARGE,GCP_Cloud_Network_LARGE)
GCP_CLOUD_ARMOR_LARGE(GCP_Cloud_Armor_LARGE,GCP_Cloud_Armor_LARGE)
GCP_CLOUD_VPN_LARGE(GCP_Cloud_VPN_LARGE,GCP_Cloud_VPN_LARGE)
GCP_CLOUD_EXTERNAL_IP_ADDRESSES_LARGE(GCP_Cloud_External_IP_Addresses_LARGE,GCP_Cloud_External_IP_Addresses_LARGE)
GCP_PARTNER_INTERCONNECT_LARGE(GCP_Partner_Interconnect_LARGE,GCP_Partner_Interconnect_LARGE)
GCP_VIRTUAL_PRIVATE_CLOUD_LARGE(GCP_Virtual_Private_Cloud_LARGE,GCP_Virtual_Private_Cloud_LARGE)
GCP_CLOUD_DNS_LARGE(GCP_Cloud_DNS_LARGE,GCP_Cloud_DNS_LARGE)
GCP_PREMIUM_NETWORK_TIER_LARGE(GCP_Premium_Network_Tier_LARGE,GCP_Premium_Network_Tier_LARGE)
GCP_CLOUD_FIREWALL_RULES_LARGE(GCP_Cloud_Firewall_Rules_LARGE,GCP_Cloud_Firewall_Rules_LARGE)
GCP_CLOUD_CDN_LARGE(GCP_Cloud_CDN_LARGE,GCP_Cloud_CDN_LARGE)
GCP_CLOUD_ROUTES_LARGE(GCP_Cloud_Routes_LARGE,GCP_Cloud_Routes_LARGE)
GCP_DEDICATED_INTERCONNECT_LARGE(GCP_Dedicated_Interconnect_LARGE,GCP_Dedicated_Interconnect_LARGE)
GCP_CLOUD_ROUTER_LARGE(GCP_Cloud_Router_LARGE,GCP_Cloud_Router_LARGE)
GCP_CLOUD_BIGTABLE_LARGE(GCP_Cloud_Bigtable_LARGE,GCP_Cloud_Bigtable_LARGE)
GCP_CLOUD_SPANNER_LARGE(GCP_Cloud_Spanner_LARGE,GCP_Cloud_Spanner_LARGE)
GCP_CLOUD_SQL_LARGE(GCP_Cloud_SQL_LARGE,GCP_Cloud_SQL_LARGE)
GCP_PERSISTENT_DISK_LARGE(GCP_Persistent_Disk_LARGE,GCP_Persistent_Disk_LARGE)
GCP_CLOUD_MEMORYSTORE_LARGE(GCP_Cloud_Memorystore_LARGE,GCP_Cloud_Memorystore_LARGE)
GCP_CLOUD_FILESTORE_LARGE(GCP_Cloud_Filestore_LARGE,GCP_Cloud_Filestore_LARGE)
GCP_CLOUD_STORAGE_LARGE(GCP_Cloud_Storage_LARGE,GCP_Cloud_Storage_LARGE)
GCP_CLOUD_DATASTORE_LARGE(GCP_Cloud_Datastore_LARGE,GCP_Cloud_Datastore_LARGE)
GCP_TRANSFER_APPLIANCE_LARGE(GCP_Transfer_Appliance_LARGE,GCP_Transfer_Appliance_LARGE)
GCP_CLOUD_ENDPOINTS_LARGE(GCP_Cloud_Endpoints_LARGE,GCP_Cloud_Endpoints_LARGE)
GCP_API_MONETIZATION_LARGE(GCP_API_Monetization_LARGE,GCP_API_Monetization_LARGE)
GCP_API_ANALYTICS_LARGE(GCP_API_Analytics_LARGE,GCP_API_Analytics_LARGE)
GCP_APIGEE_SENSE_LARGE(GCP_Apigee_Sense_LARGE,GCP_Apigee_Sense_LARGE)
GCP_APIGEE_API_PLATFORM_LARGE(GCP_Apigee_API_Platform_LARGE,GCP_Apigee_API_Platform_LARGE)
GCP_DEVELOPER_PORTAL_LARGE(GCP_Developer_Portal_LARGE,GCP_Developer_Portal_LARGE)
GCP_CLOUD_IOT_CORE_LARGE(GCP_Cloud_IoT_Core_LARGE,GCP_Cloud_IoT_Core_LARGE)
GCP_CLOUD_MACHINE_LEARNING_LARGE(GCP_Cloud_Machine_Learning_LARGE,GCP_Cloud_Machine_Learning_LARGE)
GCP_CLOUD_VIDEO_INTELLIGENCE_API_LARGE(GCP_Cloud_Video_Intelligence_API_LARGE,GCP_Cloud_Video_Intelligence_API_LARGE)
GCP_CLOUD_TRANSLATION_API_LARGE(GCP_Cloud_Translation_API_LARGE,GCP_Cloud_Translation_API_LARGE)
GCP_DIALOGFLOW_ENTERPRISE_EDITION_LARGE(GCP_Dialogflow_Enterprise_Edition_LARGE,GCP_Dialogflow_Enterprise_Edition_LARGE)
GCP_CLOUD_AUTOML_LARGE(GCP_Cloud_AutoML_LARGE,GCP_Cloud_AutoML_LARGE)
GCP_CLOUD_TEXT_TO_SPEECH_LARGE(GCP_Cloud_Text_to_Speech_LARGE,GCP_Cloud_Text_to_Speech_LARGE)
GCP_CLOUD_TPU_LARGE(GCP_Cloud_TPU_LARGE,GCP_Cloud_TPU_LARGE)
GCP_CLOUD_VISION_API_LARGE(GCP_Cloud_Vision_API_LARGE,GCP_Cloud_Vision_API_LARGE)
GCP_CLOUD_JOBS_API_LARGE(GCP_Cloud_Jobs_API_LARGE,GCP_Cloud_Jobs_API_LARGE)
GCP_CLOUD_SPEECH_API_LARGE(GCP_Cloud_Speech_API_LARGE,GCP_Cloud_Speech_API_LARGE)
GCP_CLOUD_NATURAL_LANGUAGE_API_LARGE(GCP_Cloud_Natural_Language_API_LARGE,GCP_Cloud_Natural_Language_API_LARGE)
GCP_ADVANCED_SOLUTIONS_LAB_LARGE(GCP_Advanced_Solutions_Lab_LARGE,GCP_Advanced_Solutions_Lab_LARGE)
GCP_MONITORING_LARGE(GCP_Monitoring_LARGE,GCP_Monitoring_LARGE)
GCP_CLOUD_MOBILE_APP_LARGE(GCP_Cloud_Mobile_App_LARGE,GCP_Cloud_Mobile_App_LARGE)
GCP_CLOUD_DEPLOYMENT_MANAGER_LARGE(GCP_Cloud_Deployment_Manager_LARGE,GCP_Cloud_Deployment_Manager_LARGE)
GCP_TRACE_LARGE(GCP_Trace_LARGE,GCP_Trace_LARGE)
GCP_CLOUD_CONSOLE_LARGE(GCP_Cloud_Console_LARGE,GCP_Cloud_Console_LARGE)
GCP_CLOUD_SHELL_LARGE(GCP_Cloud_Shell_LARGE,GCP_Cloud_Shell_LARGE)
GCP_CLOUD_BILLING_API_LARGE(GCP_Cloud_Billing_API_LARGE,GCP_Cloud_Billing_API_LARGE)
GCP_STACKDRIVER_LARGE(GCP_Stackdriver_LARGE,GCP_Stackdriver_LARGE)
GCP_CLOUD_APIS_LARGE(GCP_Cloud_APIs_LARGE,GCP_Cloud_APIs_LARGE)
GCP_ERROR_REPORTING_LARGE(GCP_Error_Reporting_LARGE,GCP_Error_Reporting_LARGE)
GCP_DEBUGGER_LARGE(GCP_Debugger_LARGE,GCP_Debugger_LARGE)
GCP_LOGGING_LARGE(GCP_Logging_LARGE,GCP_Logging_LARGE)
GCP_CONTAINER_BUILDER_LARGE(GCP_Container_Builder_LARGE,GCP_Container_Builder_LARGE)
GCP_CLOUD_SOURCE_REPOSITORIES_LARGE(GCP_Cloud_Source_Repositories_LARGE,GCP_Cloud_Source_Repositories_LARGE)
GCP_CLOUD_TEST_LAB_LARGE(GCP_Cloud_Test_Lab_LARGE,GCP_Cloud_Test_Lab_LARGE)
GCP_CLOUD_SDK_LARGE(GCP_Cloud_SDK_LARGE,GCP_Cloud_SDK_LARGE)
GCP_CONTAINER_REGISTRY_LARGE(GCP_Container_Registry_LARGE,GCP_Container_Registry_LARGE)
GCP_CLOUD_DEPLOYMENT_MANAGER_LARGE(GCP_Cloud_Deployment_Manager_LARGE,GCP_Cloud_Deployment_Manager_LARGE)
GCP_CLOUD_RESOURCE_MANAGER_LARGE(GCP_Cloud_Resource_Manager_LARGE,GCP_Cloud_Resource_Manager_LARGE)
GCP_BEYONDCORP_LARGE(GCP_BeyondCorp_LARGE,GCP_BeyondCorp_LARGE)
GCP_KEY_MANAGEMENT_SERVICE_LARGE(GCP_Key_Management_Service_LARGE,GCP_Key_Management_Service_LARGE)
GCP_IDENTITY_AWARE_PROXY_LARGE(GCP_Identity_Aware_Proxy_LARGE,GCP_Identity_Aware_Proxy_LARGE)
GCP_CLOUD_SECURITY_COMMAND_CENTER_LARGE(GCP_Cloud_Security_Command_Center_LARGE,GCP_Cloud_Security_Command_Center_LARGE)
GCP_DATA_LOSS_PREVENTION_API_LARGE(GCP_Data_Loss_Prevention_API_LARGE,GCP_Data_Loss_Prevention_API_LARGE)
GCP_SECURITY_KEY_ENFORCEMENT_LARGE(GCP_Security_Key_Enforcement_LARGE,GCP_Security_Key_Enforcement_LARGE)
GCP_CLOUD_SECURITY_SCANNER_LARGE(GCP_Cloud_Security_Scanner_LARGE,GCP_Cloud_Security_Scanner_LARGE)
GCP_CLOUD_IAM_LARGE(GCP_Cloud_IAM_LARGE,GCP_Cloud_IAM_LARGE)
GCP_COMPUTE_ENGINE_LARGE(GCP_Compute_Engine_LARGE,GCP_Compute_Engine_LARGE)
GCP_CONTAINER_ENGINE_LARGE(GCP_Container_Engine_LARGE,GCP_Container_Engine_LARGE)
GCP_CLOUD_FUNCTIONS_LARGE(GCP_Cloud_Functions_LARGE,GCP_Cloud_Functions_LARGE)
GCP_APP_ENGINE_LARGE(GCP_App_Engine_LARGE,GCP_App_Engine_LARGE)
GCP_CONTAINER_OPTIMIZED_OS_LARGE(GCP_Container_Optimized_OS_LARGE,GCP_Container_Optimized_OS_LARGE)
GCP_GPU_LARGE(GCP_GPU_LARGE,GCP_GPU_LARGE)
GCP_CLOUD_COMPOSER_LARGE(GCP_Cloud_Composer_LARGE,GCP_Cloud_Composer_LARGE)
GCP_BIGQUERY_LARGE(GCP_BigQuery_LARGE,GCP_BigQuery_LARGE)
GCP_DATA_STUDIO_LARGE(GCP_Data_Studio_LARGE,GCP_Data_Studio_LARGE)
GCP_CLOUD_DATALAB_LARGE(GCP_Cloud_Datalab_LARGE,GCP_Cloud_Datalab_LARGE)
GCP_CLOUD_DATAPROC_LARGE(GCP_Cloud_Dataproc_LARGE,GCP_Cloud_Dataproc_LARGE)
GCP_CLOUD_DATAFLOW_LARGE(GCP_Cloud_Dataflow_LARGE,GCP_Cloud_Dataflow_LARGE)
GCP_CLOUD_DATAPREP_LARGE(GCP_Cloud_Dataprep_LARGE,GCP_Cloud_Dataprep_LARGE)
GCP_GENOMICS_LARGE(GCP_Genomics_LARGE,GCP_Genomics_LARGE)
GCP_CLOUD_PUBSUB_LARGE(GCP_Cloud_PubSub_LARGE,GCP_Cloud_PubSub_LARGE)

@enduml
